version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-db
    command: -c config_file=/etc/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_EXTRA_CONFIG: "shared_buffers=2GB"
    volumes:
    - ./postgresql.conf:/etc/postgresql.conf
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro


